#!/bin/bash

USAGE="Usage: $0 <mac/ubuntu>"

if [ $# -ne 1 ]; then
    echo $USAGE
    exit 1
fi

if [ "$1" == "mac" ]; then
    bash package_installers/install_mac.sh
elif [ "$1" == "ubuntu" ]; then
    bash package_installers/install_ubuntu.sh
elif [ "$1" == "purdue" ]; then
    bash package_installers/install_purdue.sh
else
    echo $USAGE
    exit 1
fi

cd setup_scripts
for filename in ./*; do
    bash $filename
done

cd ../dotfiles
bash apply.sh

cd ../

# Add any additional logic here if required

# To install vim plugins
echo "Do you want to install vim plugins listed in resources/vim_plugins.txt? (y/any_other_key)"
read response
if [ "$response" == "y" ]; then
    echo "installing plugins"
    cd utils/
    bash vpi_from_file.sh
    cd ../
else
    echo "received other. skipping plugin install"
fi

echo "Exiting."
